#!/bin/bash

title=$1
titleSlug=$(echo "${title}" | sed 's/ /-/g' | sed -e 's/\(.*\)/\L\1/')
dir="$(date -u +%Y-%m-%d)-${titleSlug}"

header=$(cat <<- EOF
---
title: $title
author: James Santucci
patat:

    wrap: true
    margins:
        left: 5
        right: 5
    images:
        backend: auto
    speakerNotes:
      file: ./notes.md
---
EOF
)

mkdir "${dir}"

echo "${header}" > "${dir}/${titleSlug}.md"
